header: "*Laporan Omzet Harian*"
footer: "-- OmziNS"
services:
  - name: "💆 Izzah Salon Situbondo (Therapist)"
    module: "plugins.izzah_salon.izzah_salon_plugin_therapist_only"
    uuid: "e4283ab2-c7f2-4a09-89e6-43afb037a9ba"
  - name: "💆 Izzah Salon Situbondo (Non Therapist)"
    module: "plugins.izzah_salon.izzah_salon_plugin_non_therapist"
    uuid: "138d7924-0598-4778-bbf1-5ec5c31ae7a3"
  - name: "\n💆 Izzah Salon Situbondo (Tunai)"
    module: "plugins.izzah_salon.izzah_salon_plugin_tunai"
    uuid: "623ed339-96da-40fc-8f07-a83e2b7ba909"
  - name: "💆 Izzah Salon Situbondo (Non Tunai)"
    module: "plugins.izzah_salon.izzah_salon_plugin_non_tunai"
    uuid: "a4661cb2-e0c1-4646-80ff-47f49b4a7458"
  - name: "\n⚡ Izzah Salon Situbondo (Akumulasi Bulan Ini Tunai)"
    module: "plugins.izzah_salon.izzah_salon_plugin_accumulation_tunai"
    uuid: "0e84b42b-e789-4779-8d80-76b3ad62a98f"
  - name: "⚡ Izzah Salon Situbondo (Akumulasi Bulan Ini Non Tunai)"
    module: "plugins.izzah_salon.izzah_salon_plugin_accumulation_non_tunai"
    uuid: "1f9d72c5-1f89-40f4-bc35-1abe7e63f1a8"
  - name: "\n⚡ Izzah Salon Situbondo (Akumulasi Bulan Ini)"
    module: "plugins.izzah_salon.izzah_salon_plugin_accumulation"
    uuid: "c0b62112-c07a-489c-b320-b5d7840777d0"
  - name: "💨 Uchi Parfume Jember"
    module: "plugins.uchi_parfume.uchi_parfume_jember_plugin"
    uuid: "507f1e86-ded9-42c3-a70c-842ea7d459b1"
  - name: "⚡ Uchi Parfume Jember (Akumulasi Bulan Ini)"
    module: "plugins.uchi_parfume.uchi_parfume_jember_plugin_accumulation"
    uuid: "a019594b-ecd3-4725-b947-6bb412792911"
chats:
  - name: "OmziNS Izzah Salon"
    chat_id: ""
    schedule: "20:00:00"
    services:
      - "e4283ab2-c7f2-4a09-89e6-43afb037a9ba"
      - "138d7924-0598-4778-bbf1-5ec5c31ae7a3"
      - "623ed339-96da-40fc-8f07-a83e2b7ba909"
      - "a4661cb2-e0c1-4646-80ff-47f49b4a7458"
      - "0e84b42b-e789-4779-8d80-76b3ad62a98f"
      - "1f9d72c5-1f89-40f4-bc35-1abe7e63f1a8"
      - "c0b62112-c07a-489c-b320-b5d7840777d0"
  - name: "OmziNS Uchi Parfume Jember"
    chat_id: ""
    schedule: "22:00:00"
    services:
      - "507f1e86-ded9-42c3-a70c-842ea7d459b1"
      - "a019594b-ecd3-4725-b947-6bb412792911"